#%RAML 1.0 DataType
type: object
properties:
  bookCode:
    type: string
    example: BK234
  title:
    type: string
    example: vennello Aadapilla
  author:
    type: string
    example: Yandamuri
  booCategory:
    type: string
    example: Suspense
  readTimeInHrs:
    type: integer
    example: 20
  rentalPrice:
    type: integer
    example: 500
  rating:
    type: integer
    example: 4
  bestSeller:
    type: string
    example: no
      