#%RAML 1.0 Trait
headers:
      client_id:
        type: string
        description: API client_id 
      client_secret:
        type: string
        description: API client_secret
      x-correlation-ID:
        type: string
        description: API transaction-Id